### ISSUE TITLE
Lack of GitHub releases / precompiled binaries

### ISSUE THREAD

**Issue by Phuurl** [americanexpress/earlybird#11]
GitHub releases would allow users to download prebuilt versions of the application without having to compile it. This is especially useful for automated CI pipelines, where having to setup a Go environment and compile EarlyBird can add unnecessary overhead.

Please publish compiled binaries of EarlyBird via GitHub releases to allow them to be downloaded as part of CI pipelines. This could be implemented in a CI/CD pipeline of your choice - I'll open a PR to do it in GitHub Actions since that's probably the easiest and doesn't require any external services.

**Comment by asishrs** [comment]
v1.25.0 released.
