### ISSUE TITLE
Base directory should be ignored during ignore matching

### ISSUE THREAD

**Issue by spaluchowski** [americanexpress/earlybird#14]
This is rather an enhancement than a bug, but makes things more clear

As of now whole path is being checked against ignorefile
BUT
Imagine the situation that:
1. Ignore file contains entry "*/test/*" 
2. User uses his /var/lib/test/projects/ directory to download his projects into
Then when Earlybird is executed with parameter: -path " /var/lib/test/projects/" it will ignore all project files, nothing will be scanned

Proposed remediation:
Base directory path should be removed from matching against ignored patterns

**Comment by grinish21** [comment]
@spaluchowski Thanks for reporting. We will take a look into this.
