### ISSUE TITLE
__tests__/integration.spec.js

### ISSUE THREAD

**Issue by IchspontenEr** [americanexpress/earlybird#17]
__tests__/integration.spec.js
![Void Design (1).gif](https://user-images.githubusercontent.com/30199631/115081387-75cd3380-9f04-11eb-9c20-f4ebd3ae0db7.gif)

_Originally posted by @IchspontenEr in https://github.com/americanexpress/jest-image-snapshot/pull/230#discussion_r615110104_

**Comment by grinish21** [comment]
Possible Spam
