### ISSUE TITLE
Wrong verbose information about scanned files

### ISSUE THREAD

**Issue by spaluchowski** [americanexpress/earlybird#29]
When I scan folder with 4 files I see in log:

> Reading file
> Reading file  /mnt/c/git-repo/earlybird/verify/.ge_ignore
> Reading file  /mnt/c/git-repo/earlybird/verify/checkfile.properties
> Reading file  /mnt/c/git-repo/earlybird/verify/checkfile2.properties
>         ***** Total issues found *****
>             0 TOTAL ISSUES
> 
> 4 files scanned in 18.7711ms

The first entry is "Reading file" without the data of the file in folder.

**Comment by grinish21** [comment]
Looking into this... will share the update soon

**Comment by aschaef19** [comment]
I'm not able to replicate this issue locally, can you share more information about the steps you took for this to occur?
