### ISSUE TITLE
meta: Comparison to gitleaks? 

### ISSUE THREAD

**Issue by adamdecaf** [americanexpress/earlybird#4]
👋 Cool project! I was curious how earlybird compares to other projects like gitleaks? I see earlybird can scan a bit more types of targets, but are the patterns both recognize the same? I've used gitleaks for a while and am curious to adopt both tools.

Project: https://github.com/zricethezav/gitleaks

**Comment by digitaliceberg** [comment]
I'm not completely certain about the coverage the default configuration gitleaks provides. But we've compared Earlybird to other open source tools in the past, we have a bit more rules resulting in better coverage. Performance is higher as well due to it's concurrent design.

**Comment by scooterhanson** [comment]
One of the things we're proud of with EarlyBird is the false-positive engine with customizable regex rules for both matching and rejecting hits.  We have been running EB against internal repos and file stores for well over a year and we've been fine tuning the rules as we go along.

**Comment by adamdecaf** [comment]
Cool! Thanks for the comparison. Excited to try out earlybird
