### ISSUE TITLE
Ignore false positive string

### ISSUE THREAD

**Issue by Cr0n1c** [americanexpress/earlybird#46]
I see that we have a way of ignoring a file. Can we introduce a way to ignore a string as well? 

example: in my .env.example I have placeholders

   my_secret=ThisIsASecretToReplace

I want them to see this in the first run and then add "ThisIsASecretToReplace" to an exception list. By doing this, it still forces them to think about the data they are putting in .env.example and will always require the initial review of the finding. Currently I have to ignore the file .env.example altogether which means if someone actually puts a secret in there that is valid then no one will be monitoring (outside of the PR review).

**Comment by grinish21** [comment]
you can add a custom false-positive to ignore the specific finding you want . This might help -> https://github.com/americanexpress/earlybird/blob/main/docs/FALSEPOSITIVES.md

**Comment by grinish21** [comment]
No response from user
