### ISSUE TITLE
Need more details on HTTP API usage

### ISSUE THREAD

**Issue by jagdishkulkarni** [americanexpress/earlybird#50]
1. Is docker image available for this?
2. Can you please provide details on how to use HTTP APIs with sample payloads?

**Comment by grinish21** [comment]
1. Docker image public not available. We are planning to add a dockerfile so you can use the image incase you want it.
2. Is this document not enough?? -> https://github.com/americanexpress/earlybird/blob/main/docs/REST.md
Will work with the team to see how we can improve this. 
just an example to scan a file with curl ->
`curl -L -X POST 'http://localhost:3000/scan' \
-F 'scan=@/Users/myuser/myfile.txt'`

**Comment by grinish21** [comment]
closed due to no response. The document has been updated with curl examples.
