### ISSUE TITLE
Configuration in default path is mandatory to launch the tool

### ISSUE THREAD

**Issue by spaluchowski** [americanexpress/earlybird#8]
Even if configuration parameter is set in command line the default configuration path is still trying to load.
And if this path is not present earlybird fails to launch with error:
"Failed to load Earlybird configopen /var/lib/jenkins/.go-earlybird/earlybird.json: no such file or directory"

Expected:
If configuration path is provided in command line, the default configuration path should not be checked.

Version: 1.24.6

**Comment by grinish21** [comment]
looks like a bug on our end. fix coming soon to skip loading of default configuration when configuration path is provided.

**Comment by D0n9** [comment]
I encountered the same problem, is there a solution;

**Comment by D0n9** [comment]
> I encountered the same problem, is there a solution;

@grinish21  @asishrs , Is there any repair plan for this issue?
