### ISSUE TITLE
Configuration option to hide value from Console/Log 

### ISSUE THREAD

**Issue by asishrs** [americanexpress/earlybird#81]
Earlybird currently displays the Line number and Value as part of the output. 

Considering the Values have sensitive data and most integrations via CICD ship these logs to systems like DataDog and Splunk,  I am proposing a config in earlybird.json to control this. This is in align with OWAP [Logging - Data to Exclude](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html)

`"show_value_in_result": false`
The default should be "no value, " allowing users to override this. 

EarlyBird Version: 3.16.0
Operating System: macOS 14.0

**Comment by utsavmaniyar** [comment]
You can use `-suppress` flag to hide finding from result in console.

For more information use https://github.com/americanexpress/earlybird/blob/main/docs/USAGE.md#usage

**Comment by asishrs** [comment]
Thanks! (also sorry for not checking the options)
