### ISSUE TITLE
Cloning of git repository leaves files in temporary directory

### ISSUE THREAD

**Issue by spaluchowski** [americanexpress/earlybird#9]
After data is being downloaded using -git flag to temporary directory it is not being removed after data check.
I think that the expected behavior should be that the data is removed from the temporary location after checking presence of sensitive data. 

The problem is that if I am running check against many code repositories temp directory grows significantly and I need to have additional monitoring activity to erase temporary data. 

Version 1.24.6

**Comment by asishrs** [comment]
Thanks for reporting. We will take a look into this.

**Comment by grinish21** [comment]
@spaluchowski I am unable to recreate the issue with the `-git` flag. It removes the tmp directory once the scan is complete. Any pointers on how i can re-create the issue.

**Comment by grinish21** [comment]
@spaluchowski any thoughts on the issue? Can't recreate the bug.

**Comment by grinish21** [comment]
Unable to create the issue and lack of response.
